#Create an alias for the container built from the node:alpine base image
FROM node:alpine as builder

#Setting the working directory inside the container to be the same name as our app on our local machine.
WORKDIR "/test-ui"

#Copying our package.json file from our local machine to the working directory inside the docker container.
COPY package*.json ./

#Installing the dependencies listed in our package.json file.
RUN npm install

#Copying our project files from our local machine to the working directory in our container.
COPY . .

#Setting the default RUN command for our built container to run our test suite.
CMD ["npm", "run", "test", "--", "--coverage"]